/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// src/main.ts
__export(exports, {
  default: () => HledgerPlugin
});
var import_obsidian8 = __toModule(require("obsidian"));

// src/settings.ts
var import_obsidian = __toModule(require("obsidian"));
var DEFAULT_SETTINGS = {
  dailyNotesFolder: "",
  dailyNotesDateFormat: "YYYY-MM-DD",
  transactionHeader: "## Transactions",
  currencies: ["$", "\u20AC", "\xA3", "\xA5", "\u20B9"],
  includeDateInTransactions: true,
  transactionLineLength: 80,
  amountFormat: "comma-dot",
  currencyPlacement: "prepend",
  currencySpacing: true,
  hledgerFolder: "",
  accountsFile: "accounts.md",
  hledgerDateFormat: "YYYY-MM-DD"
};
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(inputStr) {
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder).map((folder) => folder.path);
    if (inputStr) {
      return folders.filter((folder) => folder.toLowerCase().contains(inputStr.toLowerCase()));
    }
    return folders;
  }
  renderSuggestion(value, el) {
    el.setText(value);
  }
  selectSuggestion(value, evt) {
    this.inputEl.value = value;
    this.inputEl.trigger("input");
    this.close();
  }
};
var HledgerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Hledger folder path").setDesc("Path to the folder in your Obsidian vault where hledger files will be stored").addSearch((search) => {
      search.setPlaceholder("hledger").setValue(this.plugin.settings.hledgerFolder).onChange(async (value) => {
        this.plugin.settings.hledgerFolder = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, search.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("Hledger date format").setDesc("Format for dates in hledger journal entries (using moment.js format)").addText((text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.hledgerDateFormat).onChange(async (value) => {
      this.plugin.settings.hledgerDateFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Accounts file name").setDesc("Name of the accounts file in Hledger folder that will be used for account autosuggestion").addText((text) => text.setPlaceholder("accounts.md").setValue(this.plugin.settings.accountsFile).onChange(async (value) => {
      this.plugin.settings.accountsFile = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily notes").setHeading();
    new import_obsidian.Setting(containerEl).setName("Daily notes folder").setDesc("Path to the folder where daily transaction notes will be stored").addSearch((search) => {
      search.setPlaceholder("daily/transactions").setValue(this.plugin.settings.dailyNotesFolder).onChange(async (value) => {
        this.plugin.settings.dailyNotesFolder = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, search.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("Daily notes date format").setDesc("Format for daily note filenames (using moment.js format)").addText((text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dailyNotesDateFormat).onChange(async (value) => {
      this.plugin.settings.dailyNotesDateFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Transaction section header").setDesc("Header text for the transactions section in daily notes").addText((text) => text.setPlaceholder("## Transactions").setValue(this.plugin.settings.transactionHeader).onChange(async (value) => {
      this.plugin.settings.transactionHeader = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Transactions").setHeading();
    new import_obsidian.Setting(containerEl).setName("Currencies").setDesc("List of currencies (comma-separated)").addText((text) => text.setPlaceholder("$,\u20AC,\xA3,\xA5,\u20B9").setValue(this.plugin.settings.currencies.join(",")).onChange(async (value) => {
      this.plugin.settings.currencies = value.split(",").map((c) => c.trim());
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Include date in daily transactions").setDesc("Whether to include the date in each transaction entry in daily notes").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeDateInTransactions).onChange(async (value) => {
      this.plugin.settings.includeDateInTransactions = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Transaction line length").setDesc("Maximum length of transaction lines").addText((text) => text.setPlaceholder("80").setValue(this.plugin.settings.transactionLineLength.toString()).onChange(async (value) => {
      const length = parseInt(value);
      if (!isNaN(length)) {
        this.plugin.settings.transactionLineLength = length;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian.Setting(containerEl).setName("Amount format").setDesc("Format for numbers in transactions").addDropdown((dropdown) => dropdown.addOption("comma-dot", "1,234.56").addOption("space-comma", "1 234,56").addOption("dot-comma", "1.234,56").setValue(this.plugin.settings.amountFormat).onChange(async (value) => {
      this.plugin.settings.amountFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Currency placement").setDesc("Where to place the currency symbol").addDropdown((dropdown) => dropdown.addOption("prepend", "Before amount ($ 123.45)").addOption("append", "After amount (123.45 $)").setValue(this.plugin.settings.currencyPlacement).onChange(async (value) => {
      this.plugin.settings.currencyPlacement = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Currency spacing").setDesc("Add space between currency symbol and amount").addToggle((toggle) => toggle.setValue(this.plugin.settings.currencySpacing).onChange(async (value) => {
      this.plugin.settings.currencySpacing = value;
      await this.plugin.saveSettings();
    }));
  }
};

// src/ui/entry-modal.ts
var import_obsidian2 = __toModule(require("obsidian"));
var HledgerEntryModal = class extends import_obsidian2.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.accounts = [];
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.initializeDefaultValues();
  }
  initializeDefaultValues() {
    this.setInitialDate();
    this.description = "";
    this.entries = [
      { account: "", amount: 0, currency: this.settings.currencies[0] },
      { account: "", amount: 0, currency: this.settings.currencies[0] }
    ];
    this.isExchange = false;
    this.exchangeAmount = null;
  }
  setInitialDate() {
    const activeFile = this.app.workspace.getActiveFile();
    if (activeFile) {
      const basename = activeFile.basename.replace(".md", "");
      const dateFormat = this.settings.dailyNotesDateFormat.includes("/") ? this.settings.dailyNotesDateFormat.split("/").pop() || this.settings.dailyNotesDateFormat : this.settings.dailyNotesDateFormat;
      const fileNameDate = (0, import_obsidian2.moment)(basename, dateFormat, true);
      if (fileNameDate.isValid()) {
        this.date = fileNameDate.format("YYYY-MM-DD");
      } else {
        this.date = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
      }
    } else {
      this.date = (0, import_obsidian2.moment)().format("YYYY-MM-DD");
    }
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("hledger-modal");
    await this.loadAccounts();
    this.createModalHeader(contentEl);
    const descriptionRow = contentEl.createDiv("hledger-description-row");
    this.createDescriptionInput(descriptionRow);
    const entriesContainer = contentEl.createDiv("hledger-entries-container");
    this.renderAccountEntries(entriesContainer);
    this.createModalButtons(contentEl, entriesContainer);
    this.setupKeyboardShortcuts(contentEl);
  }
  createModalHeader(contentEl) {
    const dateRow = contentEl.createDiv({ cls: "hledger-date-row" });
    const dateInput = dateRow.createEl("input", {
      type: "date",
      value: this.date,
      cls: "hledger-date-input"
    });
    const typeToggle = dateRow.createEl("select", {
      cls: "dropdown hledger-type-toggle"
    });
    typeToggle.createEl("option", {
      text: "Transaction",
      value: "transaction"
    });
    typeToggle.createEl("option", {
      text: "Exchange",
      value: "exchange"
    });
    typeToggle.value = this.isExchange ? "exchange" : "transaction";
    dateInput.addEventListener("change", (e) => {
      const target = e.target;
      this.date = target.value;
    });
    typeToggle.addEventListener("change", (e) => {
      const target = e.target;
      this.handleTypeToggle(target.value === "exchange", contentEl);
    });
  }
  createDescriptionInput(container) {
    const descriptionInput = container.createEl("input", {
      type: "text",
      placeholder: "Description",
      value: this.description,
      cls: "text-input hledger-description-input"
    });
    descriptionInput.addEventListener("change", (e) => {
      const target = e.target;
      this.description = target.value;
    });
    if (!this.isExchange) {
      const currencySelect = container.createEl("select", {
        cls: "dropdown hledger-transaction-currency-select"
      });
      this.settings.currencies.forEach((currency) => {
        const option = currencySelect.createEl("option", {
          text: currency,
          value: currency
        });
        if (currency === this.entries[0].currency) {
          option.selected = true;
        }
      });
      currencySelect.addEventListener("change", (e) => {
        const target = e.target;
        this.entries.forEach((entry) => {
          entry.currency = target.value;
        });
      });
    }
    descriptionInput.focus();
  }
  handleTypeToggle(isExchange, contentEl) {
    this.isExchange = isExchange;
    const entriesContainer = contentEl.querySelector(".hledger-entries-container");
    const leftButtons = contentEl.querySelector(".hledger-left-buttons");
    const descriptionRow = contentEl.querySelector(".hledger-description-row");
    if (descriptionRow) {
      const currentDescription = this.description;
      descriptionRow.empty();
      this.description = currentDescription;
      this.createDescriptionInput(descriptionRow);
    }
    if (this.isExchange) {
      this.entries = [
        { account: "", amount: 0, currency: this.settings.currencies[0] },
        { account: "", amount: 0, currency: this.settings.currencies[1] }
      ];
      const addButton = leftButtons.querySelector(".hledger-add-account-button");
      if (addButton) {
        addButton.remove();
      }
    } else {
      this.entries = [
        { account: "", amount: 0, currency: this.settings.currencies[0] },
        { account: "", amount: 0, currency: this.settings.currencies[0] }
      ];
      if (!leftButtons.querySelector(".hledger-add-account-button")) {
        this.createAddButton(leftButtons, entriesContainer);
      }
    }
    this.renderAccountEntries(entriesContainer);
  }
  createModalButtons(contentEl, entriesContainer) {
    const buttonsContainer = contentEl.createDiv("hledger-buttons-container");
    const leftButtons = buttonsContainer.createDiv("hledger-left-buttons");
    if (!this.isExchange) {
      this.createAddButton(leftButtons, entriesContainer);
    }
    const rightButtons = buttonsContainer.createDiv("hledger-right-buttons");
    const submitAndNewButton = rightButtons.createEl("button", {
      cls: "mod-cta",
      text: "Submit + New"
    });
    submitAndNewButton.addEventListener("click", () => this.handleSubmitAndNew());
    const submitButton = rightButtons.createEl("button", {
      cls: "mod-cta",
      text: "Submit"
    });
    submitButton.addEventListener("click", () => this.handleSubmit());
  }
  createAddButton(container, entriesContainer) {
    const addAccountButton = container.createEl("button", {
      cls: "hledger-add-account-button"
    });
    const svgEl = this.createSVGIcon("plus", "M5 12h14", "M12 5v14");
    addAccountButton.empty();
    addAccountButton.appendChild(svgEl);
    addAccountButton.addEventListener("click", () => {
      this.addNewEntry(entriesContainer);
    });
    return addAccountButton;
  }
  addNewEntry(entriesContainer) {
    const lastEntry = this.entries[this.entries.length - 1];
    const totalAmount = this.entries.reduce((sum, entry) => sum + entry.amount, 0);
    this.entries.push({
      account: "",
      amount: -totalAmount,
      currency: lastEntry.currency
    });
    this.renderAccountEntries(entriesContainer);
    setTimeout(() => {
      const newAccountInput = entriesContainer.querySelectorAll(".hledger-account-input");
      if (newAccountInput && newAccountInput.length > 0) {
        const lastAccountInput = newAccountInput[newAccountInput.length - 1];
        lastAccountInput.focus();
      }
    }, 10);
  }
  createSVGIcon(iconName, ...pathData) {
    const SVG_NS = "http://www.w3.org/2000/svg";
    const svgEl = document.createElementNS(SVG_NS, "svg");
    svgEl.setAttribute("xmlns", SVG_NS);
    svgEl.setAttribute("width", "24");
    svgEl.setAttribute("height", "24");
    svgEl.setAttribute("viewBox", "0 0 24 24");
    svgEl.setAttribute("fill", "none");
    svgEl.setAttribute("stroke", "currentColor");
    svgEl.setAttribute("stroke-width", "2");
    svgEl.setAttribute("stroke-linecap", "round");
    svgEl.setAttribute("stroke-linejoin", "round");
    svgEl.setAttribute("class", `svg-icon lucide-${iconName}`);
    pathData.forEach((d) => {
      const path = document.createElementNS(SVG_NS, "path");
      path.setAttribute("d", d);
      svgEl.appendChild(path);
    });
    return svgEl;
  }
  createTrashIcon() {
    const svg = this.createSVGIcon("trash-2", "M3 6h18", "M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6", "M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2");
    const SVG_NS = "http://www.w3.org/2000/svg";
    const line1 = document.createElementNS(SVG_NS, "line");
    line1.setAttribute("x1", "10");
    line1.setAttribute("y1", "11");
    line1.setAttribute("x2", "10");
    line1.setAttribute("y2", "17");
    svg.appendChild(line1);
    const line2 = document.createElementNS(SVG_NS, "line");
    line2.setAttribute("x1", "14");
    line2.setAttribute("y1", "11");
    line2.setAttribute("x2", "14");
    line2.setAttribute("y2", "17");
    svg.appendChild(line2);
    return svg;
  }
  setupKeyboardShortcuts(contentEl) {
    contentEl.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.handleSubmit();
      }
    });
  }
  handleSubmitAndNew() {
    if (this.validateForm()) {
      this.onSubmit(this.date, this.description, this.entries);
      const newModal = new HledgerEntryModal(this.app, this.settings, this.onSubmit);
      this.close();
      newModal.open();
    }
  }
  validateForm() {
    const emptyAccounts = this.entries.filter((entry) => !entry.account.trim());
    if (emptyAccounts.length > 0) {
      new import_obsidian2.Notice("Please fill in all account names");
      return false;
    }
    const emptyAmounts = this.entries.filter((entry) => {
      const amountInput = entry.amount !== void 0 ? entry.amount.toString() : "";
      return amountInput === "0" || amountInput === "" || amountInput.trim() === "" || isNaN(entry.amount);
    });
    if (this.isExchange) {
      if (emptyAmounts.length > 0) {
        new import_obsidian2.Notice("Please fill in all amount fields");
        return false;
      }
      if (this.entries.every((entry) => entry.amount === 0)) {
        new import_obsidian2.Notice("At least one amount must be non-zero in exchange mode");
        return false;
      }
    } else {
      if (emptyAmounts.length > 0) {
        new import_obsidian2.Notice("Please fill in all amount fields with valid numbers");
        return false;
      }
      const totalAmount = this.entries.reduce((sum, entry) => sum + entry.amount, 0);
      const epsilon = 1e-4;
      if (Math.abs(totalAmount) > epsilon) {
        new import_obsidian2.Notice(`Transaction does not balance. Total is ${totalAmount.toFixed(2)}`);
        return false;
      }
    }
    return true;
  }
  handleSubmit() {
    if (this.validateForm()) {
      this.onSubmit(this.date, this.description, this.entries);
      this.close();
    }
  }
  async loadAccounts() {
    if (!this.settings.accountsFile || !this.settings.hledgerFolder) {
      return;
    }
    try {
      const accountsPath = `${this.settings.hledgerFolder}/${this.settings.accountsFile}`;
      const file = this.app.vault.getAbstractFileByPath(accountsPath);
      if (file instanceof import_obsidian2.TFile) {
        const content = await this.app.vault.read(file);
        this.accounts = content.split("\n").map((line) => line.trim()).filter((line) => line.startsWith("account ")).map((line) => {
          const match = line.match(/^account\s+([^;]+)/);
          return match ? match[1].trim() : null;
        }).filter((account) => account !== null);
      }
    } catch (error) {
      console.error("Error loading accounts file:", error);
    }
  }
  renderAccountEntries(container) {
    container.empty();
    this.entries.forEach((entry, index) => {
      const entryDiv = container.createDiv("hledger-entry-row");
      this.createAccountInput(entryDiv, entry, index, container);
      this.createAmountInput(entryDiv, entry, index, container);
      if (this.isExchange) {
        this.createCurrencySelect(entryDiv, entry);
      }
      if (this.entries.length > 2 && !this.isExchange) {
        this.createDeleteButton(entryDiv, index, container);
      }
    });
  }
  createAccountInput(entryDiv, entry, index, container) {
    const accountInputContainer = entryDiv.createDiv("hledger-account-input-container");
    const accountInput = accountInputContainer.createEl("input", {
      type: "text",
      value: entry.account,
      placeholder: "Account",
      cls: "text-input hledger-account-input"
    });
    const suggestContainer = accountInputContainer.createDiv("hledger-account-suggest-container hidden");
    this.setupAccountAutocomplete(accountInput, suggestContainer, entryDiv, entry);
  }
  setupAccountAutocomplete(accountInput, suggestContainer, entryDiv, entry) {
    const showSuggestions = () => {
      const inputValue = accountInput.value.toLowerCase();
      if (!inputValue) {
        suggestContainer.addClass("hidden");
        return;
      }
      const matches = this.filterAndSortAccounts(inputValue);
      if (matches.length === 0) {
        suggestContainer.addClass("hidden");
        return;
      }
      this.displaySuggestions(matches, suggestContainer, accountInput, entryDiv, entry);
    };
    const selectSuggestion = (account) => {
      entry.account = account;
      accountInput.value = account;
      suggestContainer.addClass("hidden");
      const amountInput = entryDiv.querySelector(".hledger-amount-input");
      if (amountInput) {
        amountInput.focus();
      }
    };
    this.setupAccountAutocompleteEvents(accountInput, suggestContainer, showSuggestions, selectSuggestion);
    accountInput.addEventListener("change", (e) => {
      const target = e.target;
      entry.account = target.value;
    });
  }
  filterAndSortAccounts(inputValue) {
    return this.accounts.filter((account) => account.toLowerCase().includes(inputValue)).sort((a, b) => {
      const aStartsWithInput = a.toLowerCase().startsWith(inputValue) ? 0 : 1;
      const bStartsWithInput = b.toLowerCase().startsWith(inputValue) ? 0 : 1;
      if (aStartsWithInput !== bStartsWithInput) {
        return aStartsWithInput - bStartsWithInput;
      }
      const aIndex = a.toLowerCase().indexOf(inputValue);
      const bIndex = b.toLowerCase().indexOf(inputValue);
      if (aIndex !== bIndex) {
        return aIndex - bIndex;
      }
      return a.length - b.length;
    }).slice(0, 10);
  }
  displaySuggestions(matches, suggestContainer, accountInput, entryDiv, entry) {
    suggestContainer.empty();
    suggestContainer.removeClass("hidden");
    const selectSuggestion = (account) => {
      entry.account = account;
      accountInput.value = account;
      suggestContainer.addClass("hidden");
      const amountInput = entryDiv.querySelector(".hledger-amount-input");
      if (amountInput) {
        amountInput.focus();
      }
    };
    matches.forEach((account, idx) => {
      const item = suggestContainer.createDiv({
        cls: idx === 0 ? "hledger-account-suggest-item selected" : "hledger-account-suggest-item"
      });
      item.textContent = account;
      item.addEventListener("mousedown", (e) => {
        e.preventDefault();
        selectSuggestion(account);
      });
      item.addEventListener("touchend", (e) => {
        e.preventDefault();
        selectSuggestion(account);
      });
      item.addEventListener("mouseenter", () => {
        suggestContainer.querySelectorAll(".hledger-account-suggest-item").forEach((el) => {
          el.removeClass("selected");
        });
        item.addClass("selected");
      });
    });
  }
  setupAccountAutocompleteEvents(accountInput, suggestContainer, showSuggestions, selectSuggestion) {
    accountInput.addEventListener("keydown", (e) => {
      this.handleSuggestionKeyboardNavigation(e, suggestContainer, showSuggestions, selectSuggestion);
    });
    accountInput.addEventListener("input", showSuggestions);
    accountInput.addEventListener("focus", showSuggestions);
    accountInput.addEventListener("blur", (e) => {
      setTimeout(() => {
        if (!suggestContainer.contains(document.activeElement)) {
          suggestContainer.addClass("hidden");
        }
      }, 300);
    });
    suggestContainer.addEventListener("mousedown", (e) => {
      e.preventDefault();
    });
    suggestContainer.addEventListener("touchstart", (e) => {
      e.stopPropagation();
    });
    accountInput.addEventListener("click", () => {
      if (!accountInput.value) {
        showSuggestions();
      }
    });
  }
  handleSuggestionKeyboardNavigation(e, suggestContainer, showSuggestions, selectSuggestion) {
    if (suggestContainer.hasClass("hidden")) {
      if (e.key === "ArrowDown") {
        showSuggestions();
        e.preventDefault();
      }
      return;
    }
    const items = suggestContainer.querySelectorAll(".hledger-account-suggest-item");
    const selectedItem = suggestContainer.querySelector(".selected");
    let selectedIndex = Array.from(items).indexOf(selectedItem);
    switch (e.key) {
      case "ArrowDown":
        if (selectedIndex < items.length - 1) {
          items[selectedIndex].removeClass("selected");
          items[selectedIndex + 1].addClass("selected");
          const nextItem = items[selectedIndex + 1];
          const containerRect = suggestContainer.getBoundingClientRect();
          const itemRect = nextItem.getBoundingClientRect();
          if (itemRect.bottom > containerRect.bottom) {
            suggestContainer.scrollTop += itemRect.bottom - containerRect.bottom;
          }
        }
        e.preventDefault();
        break;
      case "ArrowUp":
        if (selectedIndex > 0) {
          items[selectedIndex].removeClass("selected");
          items[selectedIndex - 1].addClass("selected");
          const prevItem = items[selectedIndex - 1];
          const containerRect = suggestContainer.getBoundingClientRect();
          const itemRect = prevItem.getBoundingClientRect();
          if (itemRect.top < containerRect.top) {
            suggestContainer.scrollTop -= containerRect.top - itemRect.top;
          }
        }
        e.preventDefault();
        break;
      case "Enter":
        if (selectedItem) {
          selectSuggestion(selectedItem.textContent || "");
          e.preventDefault();
        }
        break;
      case "Escape":
        suggestContainer.addClass("hidden");
        e.preventDefault();
        break;
    }
  }
  createAmountInput(entryDiv, entry, index, container) {
    const amountInput = entryDiv.createEl("input", {
      type: "text",
      value: entry.amount ? entry.amount.toString() : "",
      placeholder: "Amount",
      cls: "text-input hledger-amount-input"
    });
    amountInput.addEventListener("input", (e) => {
      const target = e.target;
      let value = target.value.trim();
      value = this.processAmountValue(value, entry, target);
    });
    amountInput.addEventListener("change", (e) => {
      const target = e.target;
      let value = target.value.trim();
      value = this.processAmountValue(value, entry, target);
      if (index === 0 && this.entries.length === 2 && !this.isExchange) {
        this.updateSecondRowAmount(entry.amount, container);
      }
    });
  }
  processAmountValue(value, entry, inputElement) {
    if (!value.trim()) {
      entry.amount = NaN;
      return "";
    }
    let suffix = "";
    if (value.toLowerCase().endsWith("k")) {
      suffix = "k";
      value = value.slice(0, -1);
    } else if (value.toLowerCase().endsWith("m")) {
      suffix = "m";
      value = value.slice(0, -1);
    }
    if (value.includes(".")) {
      value = value.replace(/,/g, "");
    } else if ((value.match(/,/g) || []).length === 1 && !value.includes(".")) {
      value = value.replace(",", ".");
    } else {
      value = value.replace(/,/g, "");
    }
    value = value.replace(/[^\d.-]/g, "");
    const decimalPoints = (value.match(/\./g) || []).length;
    if (decimalPoints > 1) {
      const parts = value.split(".");
      value = parts[0] + "." + parts.slice(1).join("");
    }
    value = value + suffix;
    if (value.toLowerCase().endsWith("k")) {
      value = value.slice(0, -1);
      entry.amount = Math.round((parseFloat(value) || 0) * 1e3);
      inputElement.value = entry.amount.toString();
    } else if (value.toLowerCase().endsWith("m")) {
      value = value.slice(0, -1);
      entry.amount = Math.round((parseFloat(value) || 0) * 1e6);
      inputElement.value = entry.amount.toString();
    } else {
      entry.amount = parseFloat(value) || 0;
      if (value !== inputElement.value) {
        inputElement.value = value;
      }
    }
    return value;
  }
  updateSecondRowAmount(firstRowAmount, container) {
    const secondRow = this.entries[1];
    const secondAmountInput = container.querySelectorAll(".hledger-amount-input")[1];
    if (secondAmountInput && !Number.isNaN(firstRowAmount) && (secondAmountInput.value === "" || secondAmountInput.value === "0")) {
      secondRow.amount = -firstRowAmount;
      secondAmountInput.value = (-firstRowAmount).toString();
    }
  }
  createCurrencySelect(entryDiv, entry) {
    const currencySelect = entryDiv.createEl("select", {
      cls: "dropdown hledger-currency-select"
    });
    this.settings.currencies.forEach((currency) => {
      const option = currencySelect.createEl("option", {
        text: currency,
        value: currency
      });
      if (currency === entry.currency) {
        option.selected = true;
      }
    });
    currencySelect.addEventListener("change", (e) => {
      const target = e.target;
      entry.currency = target.value;
    });
  }
  createDeleteButton(entryDiv, index, container) {
    const deleteButton = entryDiv.createEl("button", {
      cls: "clickable-icon hledger-delete-button"
    });
    const trashIcon = this.createTrashIcon();
    deleteButton.empty();
    deleteButton.appendChild(trashIcon);
    deleteButton.addEventListener("click", () => {
      this.entries.splice(index, 1);
      this.renderAccountEntries(container);
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/export-modal.ts
var import_obsidian3 = __toModule(require("obsidian"));
var HledgerExportModal = class extends import_obsidian3.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.initializeDefaultOptions();
  }
  initializeDefaultOptions() {
    const now = (0, import_obsidian3.moment)();
    this.options = {
      fromDate: (0, import_obsidian3.moment)().startOf("year").format("YYYY-MM-DD"),
      toDate: now.format("YYYY-MM-DD"),
      journalFile: now.format("YYYY") + ".journal",
      replaceExisting: false
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("hledger-export-modal");
    this.createHeader(contentEl);
    this.createDateInputs(contentEl);
    this.createFileOptions(contentEl);
    this.createExportButton(contentEl);
    contentEl.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.handleExport();
      }
    });
  }
  createHeader(contentEl) {
    contentEl.createEl("h3", { text: "Export transactions to hledger journal" });
  }
  createDateInputs(contentEl) {
    new import_obsidian3.Setting(contentEl).setName("From").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.options.fromDate);
      text.onChange((value) => this.options.fromDate = value);
    });
    new import_obsidian3.Setting(contentEl).setName("To").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.options.toDate);
      text.onChange((value) => this.options.toDate = value);
    });
  }
  createFileOptions(contentEl) {
    new import_obsidian3.Setting(contentEl).setName("Journal file").setDesc("Name for the exported journal file").addText((text) => {
      text.inputEl.setAttribute("type", "text");
      text.setPlaceholder(this.options.journalFile).setValue(this.options.journalFile).onChange((value) => {
        this.options.journalFile = value;
      });
    });
    new import_obsidian3.Setting(contentEl).setName("Replace existing").setDesc("Replace file if it already exists").addToggle((toggle) => toggle.setValue(this.options.replaceExisting).onChange((value) => {
      this.options.replaceExisting = value;
    }));
  }
  createExportButton(contentEl) {
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Export").setCta().onClick(() => this.handleExport()));
  }
  handleExport() {
    if (!this.validate()) {
      return;
    }
    this.onSubmit(this.options.fromDate, this.options.toDate, this.options.journalFile.trim(), this.options.replaceExisting);
    this.close();
  }
  validate() {
    const { fromDate, toDate, journalFile } = this.options;
    const trimmedJournalFile = journalFile.trim();
    if (!trimmedJournalFile) {
      new import_obsidian3.Notice("File name cannot be empty.");
      return false;
    }
    const invalidCharsRegex = /[\\/:*?"<>|]/;
    if (invalidCharsRegex.test(trimmedJournalFile)) {
      new import_obsidian3.Notice('File name contains invalid characters (e.g., \\ / : * ? " < > |).');
      return false;
    }
    if (!fromDate || !toDate) {
      new import_obsidian3.Notice("Please fill in all required date fields.");
      return false;
    }
    if ((0, import_obsidian3.moment)(toDate).isBefore(fromDate)) {
      new import_obsidian3.Notice("To date cannot be before from date");
      return false;
    }
    if (!trimmedJournalFile.endsWith(".journal") && !trimmedJournalFile.endsWith(".hledger") && !trimmedJournalFile.endsWith(".ledger")) {
      new import_obsidian3.Notice("File should have .journal, .hledger, or .ledger extension");
      return false;
    }
    return true;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/ui/import-modal.ts
var import_obsidian4 = __toModule(require("obsidian"));
var HledgerImportModal = class extends import_obsidian4.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.initializeDefaultOptions();
  }
  initializeDefaultOptions() {
    const now = (0, import_obsidian4.moment)();
    this.options = {
      fromDate: (0, import_obsidian4.moment)().startOf("year").format("YYYY-MM-DD"),
      toDate: now.format("YYYY-MM-DD"),
      journalFile: "hledger.journal"
    };
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("hledger-modal");
    this.createHeader(contentEl);
    this.createWarningNote(contentEl);
    this.createDateInputs(contentEl);
    this.createFileOptions(contentEl);
    this.createImportButton(contentEl);
    contentEl.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.handleImport();
      }
    });
  }
  createHeader(contentEl) {
    contentEl.createEl("h3", { text: "Import transactions from hledger journal" });
  }
  createWarningNote(contentEl) {
    contentEl.createEl("div", {
      cls: "hledger-warning-note",
      text: "Note: This action will override all transactions in your daily notes"
    });
  }
  createDateInputs(contentEl) {
    new import_obsidian4.Setting(contentEl).setName("From").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.options.fromDate).onChange((value) => {
        this.options.fromDate = value;
      });
    });
    new import_obsidian4.Setting(contentEl).setName("To").addText((text) => {
      text.inputEl.type = "date";
      text.setValue(this.options.toDate);
      text.onChange((value) => this.options.toDate = value);
    });
  }
  createFileOptions(contentEl) {
    new import_obsidian4.Setting(contentEl).setName("Journal file").setDesc("Journal file name to import transactions from").addText((text) => text.setPlaceholder(this.options.journalFile).setValue(this.options.journalFile).onChange((value) => {
      this.options.journalFile = value;
    }));
  }
  createImportButton(contentEl) {
    new import_obsidian4.Setting(contentEl).addButton((btn) => btn.setButtonText("Import").setCta().onClick(() => this.handleImport()));
  }
  handleImport() {
    if (!this.validate()) {
      return;
    }
    this.onSubmit(this.options.fromDate, this.options.toDate, this.options.journalFile.trim());
    this.close();
  }
  validate() {
    const { fromDate, toDate, journalFile } = this.options;
    const trimmedJournalFile = journalFile.trim();
    if (!trimmedJournalFile) {
      new import_obsidian4.Notice("Please enter a journal filename.");
      return false;
    }
    if (!fromDate || !toDate) {
      new import_obsidian4.Notice("Please select valid dates.");
      return false;
    }
    if ((0, import_obsidian4.moment)(toDate).isBefore(fromDate)) {
      new import_obsidian4.Notice("To date cannot be before From date.");
      return false;
    }
    if (this.settings.hledgerFolder) {
      if (!trimmedJournalFile.endsWith(".journal") && !trimmedJournalFile.endsWith(".hledger") && !trimmedJournalFile.endsWith(".ledger")) {
        new import_obsidian4.Notice("File should have .journal, .hledger, or .ledger extension");
        return false;
      }
    }
    return true;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/handlers/entry-handler.ts
function formatNumber(num, format) {
  const parts = num.toString().split(".");
  const integerPart = parts[0];
  let decimalPart = parts[1] || "00";
  if (decimalPart.length < 2) {
    decimalPart = decimalPart.padEnd(2, "0");
  }
  let thousandsSeparator;
  let decimalMark;
  switch (format) {
    case "comma-dot":
      thousandsSeparator = ",";
      decimalMark = ".";
      break;
    case "space-comma":
      thousandsSeparator = " ";
      decimalMark = ",";
      break;
    case "dot-comma":
      thousandsSeparator = ".";
      decimalMark = ",";
      break;
  }
  const formattedInteger = integerPart.replace(/\B(?=(\d{3})+(?!\d))/g, thousandsSeparator);
  return `${formattedInteger}${decimalMark}${decimalPart}`;
}
function formatAmount(amount, currency, config) {
  const isNegative = amount < 0;
  const absAmount = Math.abs(amount);
  const formattedNumber = formatNumber(absAmount, config.numberFormat);
  const space = config.currencySpacing ? " " : "";
  if (config.currencyPlacement === "prepend") {
    return isNegative ? `${currency}${space}-${formattedNumber}` : `${currency}${space}${formattedNumber}`;
  } else {
    return isNegative ? `-${formattedNumber}${space}${currency}` : `${formattedNumber}${space}${currency}`;
  }
}
function formatLine(account, amount, currency, config, exchangeAmount, exchangeCurrency) {
  const formattedAmount = formatAmount(amount, currency, config);
  let line = `${account}`;
  const paddingLength = config.lineLength - account.length - formattedAmount.length;
  const padding = " ".repeat(Math.max(0, paddingLength));
  if (exchangeAmount !== void 0 && exchangeCurrency !== void 0) {
    const formattedExchange = formatAmount(Math.abs(exchangeAmount), exchangeCurrency, config);
    line += `${padding}${formattedAmount} @@ ${formattedExchange}`;
  } else {
    line += `${padding}${formattedAmount}`;
  }
  return line;
}
function calculateDailyNotePathInfo(dateObj, baseFolder, dateFormat) {
  let fileName;
  let subFolder = "";
  if (dateFormat.includes("/")) {
    const parts = dateFormat.split("/");
    const fileFormat = parts.pop() || "";
    const folderFormat = parts.join("/");
    if (folderFormat) {
      subFolder = dateObj.format(folderFormat);
    }
    fileName = dateObj.format(fileFormat) + ".md";
  } else {
    fileName = dateObj.format(dateFormat) + ".md";
  }
  const targetFolder = subFolder ? `${baseFolder}/${subFolder}` : baseFolder;
  const cleanedTargetFolder = targetFolder.replace(/\/\//g, "/");
  const targetPath = `${cleanedTargetFolder}/${fileName}`.replace(/\/\//g, "/");
  return { targetFolder: cleanedTargetFolder, targetPath };
}
async function updateOrCreateDailyNoteHledgerSection(targetPath, transactionContent, transactionHeader, adapter) {
  try {
    const fileExists = await adapter.exists(targetPath);
    let finalContent;
    if (fileExists) {
      const file = await adapter.read(targetPath);
      const hledgerRegex = /```hledger\n([\s\S]*?)```/;
      const match = file.match(hledgerRegex);
      if (match) {
        const existingTransactions = match[1];
        const needsNewline = existingTransactions.length > 0 && !existingTransactions.endsWith("\n\n") && !existingTransactions.trim().endsWith("\n");
        const newContent = needsNewline ? "\n" + transactionContent : transactionContent;
        finalContent = file.replace(hledgerRegex, `\`\`\`hledger
${match[1]}${newContent}\`\`\``);
      } else {
        finalContent = file.trimEnd() + `

${transactionHeader}

\`\`\`hledger
${transactionContent.trimEnd()}
\`\`\``;
      }
    } else {
      finalContent = `${transactionHeader}

\`\`\`hledger
${transactionContent.trimEnd()}
\`\`\``;
    }
    await adapter.write(targetPath, finalContent);
  } catch (error) {
    console.error(`Error updating or creating daily note section in ${targetPath}:`, error);
    throw new Error(`Failed to update or create hledger section in ${targetPath}: ${error instanceof Error ? error.message : String(error)}`);
  }
}

// src/handlers/export-handler.ts
var import_obsidian6 = __toModule(require("obsidian"));

// src/utils.ts
var import_obsidian5 = __toModule(require("obsidian"));
function createDateRegexPattern(hledgerDateFormat) {
  let pattern = hledgerDateFormat.replace(/YYYY/g, "\\d{4}").replace(/YY/g, "\\d{2}").replace(/MM/g, "\\d{2}").replace(/M/g, "\\d{1,2}").replace(/DD/g, "\\d{2}").replace(/D/g, "\\d{1,2}");
  pattern = pattern.replace(/\//g, "\\/").replace(/\./g, "\\.").replace(/-/g, "\\-");
  return new RegExp(`^${pattern}`);
}
function createDateRemovalRegex(hledgerDateFormat) {
  const pattern = createDateRegexPattern(hledgerDateFormat).source;
  return new RegExp(`^${pattern.substring(1)}\\s*`);
}
function parseJournalTransactions(content, hledgerDateFormat) {
  const transactions = [];
  let currentTransactionLines = [];
  const dateRegex = createDateRegexPattern(hledgerDateFormat);
  const lines = content.split("\n");
  for (const line of lines) {
    if (dateRegex.test(line)) {
      if (currentTransactionLines.length > 0) {
        transactions.push(currentTransactionLines.join("\n"));
      }
      currentTransactionLines = [line];
    } else if (currentTransactionLines.length > 0) {
      if (line.startsWith(" ") || line.startsWith("	")) {
        currentTransactionLines.push(line);
      }
    }
  }
  if (currentTransactionLines.length > 0) {
    transactions.push(currentTransactionLines.join("\n"));
  }
  return transactions;
}
function extractTransactionDate(transaction, hledgerDateFormat) {
  const datePattern = hledgerDateFormat.replace(/[YMD]/g, "\\d").replace(/[-/]/g, "\\$&");
  const dateRegex = new RegExp(`^(${datePattern})`);
  const match = transaction.match(dateRegex);
  return match ? match[1] : null;
}
function extractHledgerBlock(fileContent) {
  const hledgerCodeBlockRegex = /```hledger\s*([\s\S]*?)```/gi;
  const blocks = [];
  let match;
  while ((match = hledgerCodeBlockRegex.exec(fileContent)) !== null) {
    blocks.push(match[1].trim());
  }
  return blocks.length > 0 ? blocks.join("\n\n") : null;
}
function normalizePath(path) {
  return path.replace(/\\/g, "/");
}
async function ensureDirectoryExists(directoryPath, adapter) {
  if (!directoryPath)
    return;
  try {
    if (!await adapter.exists(directoryPath)) {
      try {
        await adapter.mkdir(directoryPath);
      } catch (mkdirError) {
        if (!await adapter.exists(directoryPath)) {
          console.error(`Failed to create directory after checking again: ${directoryPath}`, mkdirError);
          throw new Error(`Failed to create directory ${directoryPath}`);
        }
      }
    }
  } catch (error) {
    console.error(`Error ensuring directory exists ${directoryPath}:`, error);
    if (error instanceof Error && error.message.startsWith("Failed to create directory")) {
      throw error;
    } else {
      throw new Error(`Failed to ensure directory exists ${directoryPath}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
}
function getParentDirectory(path) {
  const normalizedPath = normalizePath(path);
  const pathWithoutTrailingSlash = normalizedPath.endsWith("/") ? normalizedPath.slice(0, -1) : normalizedPath;
  const lastSlashIndex = pathWithoutTrailingSlash.lastIndexOf("/");
  if (lastSlashIndex === -1) {
    return "";
  }
  return pathWithoutTrailingSlash.substring(0, lastSlashIndex);
}

// src/handlers/export-handler.ts
function validateExportSettings(settings) {
  if (!settings.dailyNotesFolder || !settings.hledgerFolder) {
    return "Please set both daily notes and hledger folders in settings";
  }
  if (!settings.hledgerDateFormat || !settings.dailyNotesDateFormat) {
    return "Please set both hledger and daily notes date formats in settings.";
  }
  return null;
}
function splitIntoTransactions(blockContent) {
  if (!blockContent)
    return [];
  return blockContent.split(/\n\s*\n+/).map((transaction) => transaction.trim()).filter((transaction) => transaction.length > 0);
}
function formatTransaction(transactionString, formattedDate, hledgerDateFormat = "YYYY-MM-DD") {
  const lines = transactionString.split("\n");
  const firstLine = lines[0].trimEnd();
  const existingDate = extractTransactionDate(firstLine, hledgerDateFormat);
  const hasDateAlready = existingDate !== null;
  if (/\s{3,}/.test(firstLine)) {
    const indentedLines = lines.map((line) => `    ${line.trimEnd()}`);
    return `${formattedDate}
${indentedLines.join("\n")}`;
  } else if (hasDateAlready) {
    const restOfLines = lines.slice(1);
    const normalizedIndentedLines = restOfLines.map((line) => {
      const trimmedLine = line.replace(/^\s+/, "");
      return `    ${trimmedLine}`;
    });
    return `${firstLine}${normalizedIndentedLines.length > 0 ? `
${normalizedIndentedLines.join("\n")}` : ""}`;
  } else {
    const header = `${formattedDate} ${firstLine}`;
    const restOfLines = lines.slice(1);
    const indentedRest = restOfLines.map((line) => `    ${line.trimEnd()}`);
    return header + (indentedRest.length > 0 ? `
${indentedRest.join("\n")}` : "");
  }
}
async function processHledgerFile(filePath, adapter, dailyNotesDateFormat, hledgerDateFormat) {
  const processedTransactions = [];
  try {
    let parsedDate;
    if (dailyNotesDateFormat.includes("/")) {
      const pathParts = filePath.split("/");
      if (pathParts.length >= 2) {
        const dirName = pathParts[pathParts.length - 2];
        const fileName = pathParts[pathParts.length - 1].replace(/\.md$/i, "");
        const fullDateStr = `${dirName}/${fileName}`;
        parsedDate = (0, import_obsidian6.moment)(fullDateStr, dailyNotesDateFormat, true);
      }
    } else {
      const filenameWithExt = filePath.split("/").pop() || filePath;
      const filenameWithoutExt = filenameWithExt.replace(/\.md$/, "");
      parsedDate = (0, import_obsidian6.moment)(filenameWithoutExt, dailyNotesDateFormat, true);
    }
    if (!parsedDate || !parsedDate.isValid()) {
      console.warn(`Skipping file: Could not parse date from file path '${filePath}' using format '${dailyNotesDateFormat}'`);
      return [];
    }
    const formattedDate = parsedDate.format(hledgerDateFormat);
    const fileContent = await adapter.read(filePath);
    const hledgerBlock = extractHledgerBlock(fileContent);
    if (!hledgerBlock) {
      console.warn(`No hledger blocks found in file: ${filePath}`);
      return [];
    }
    const transactions = splitIntoTransactions(hledgerBlock);
    for (const transaction of transactions) {
      const formattedTransaction = formatTransaction(transaction, formattedDate, hledgerDateFormat);
      processedTransactions.push(formattedTransaction);
    }
  } catch (error) {
    console.error(`Error processing file ${filePath}:`, error);
    throw new Error(`Error processing file ${filePath}: ${error instanceof Error ? error.message : String(error)}`);
  }
  return processedTransactions;
}
async function processHledgerFiles(filteredFiles, adapter, dailyNotesDateFormat, hledgerDateFormat) {
  const processedBlocks = [];
  for (const filePath of filteredFiles) {
    try {
      const transactions = await processHledgerFile(filePath, adapter, dailyNotesDateFormat, hledgerDateFormat);
      processedBlocks.push(...transactions);
    } catch (fileError) {
      console.error(`Error processing file ${filePath}:`, fileError);
    }
  }
  return processedBlocks;
}
async function getAllFilesInFolder(folderPath, adapter) {
  const allFiles = [];
  try {
    const listResult = await adapter.list(folderPath);
    const queue = [...listResult.folders];
    allFiles.push(...listResult.files.map((file) => normalizePath(file)));
    while (queue.length > 0) {
      const currentFolder = queue.shift();
      try {
        const subFolderContent = await adapter.list(currentFolder);
        allFiles.push(...subFolderContent.files.map((file) => normalizePath(file)));
        queue.push(...subFolderContent.folders);
      } catch (subError) {
        console.warn(`Could not list folder ${currentFolder}:`, subError);
      }
    }
  } catch (error) {
    console.error(`Error listing files in ${folderPath}:`, error);
    throw new Error(`Could not access folder: ${folderPath}`);
  }
  return allFiles;
}
function filterFilesByDateRange(files, fromDateStr, toDateStr, dateFormat) {
  const fromMoment = (0, import_obsidian6.moment)(fromDateStr, "YYYY-MM-DD");
  const toMoment = (0, import_obsidian6.moment)(toDateStr, "YYYY-MM-DD");
  return files.filter((filePath) => {
    var _a;
    const normalizedFilePath = normalizePath(filePath);
    if (!normalizedFilePath.toLowerCase().endsWith(".md")) {
      return false;
    }
    if (dateFormat.includes("/")) {
      const pathParts = normalizedFilePath.split("/");
      if (pathParts.length >= 2) {
        const dirName = pathParts[pathParts.length - 2];
        const fileName = pathParts[pathParts.length - 1].replace(/\.md$/i, "");
        const formatParts = dateFormat.split("/");
        const dirFormat = formatParts[0];
        const fileFormat = formatParts[1];
        const dirDate = (0, import_obsidian6.moment)(dirName, dirFormat, true);
        if (!dirDate.isValid()) {
          return false;
        }
        const fullDateStr = `${dirName}/${fileName}`;
        const fileDate2 = (0, import_obsidian6.moment)(fullDateStr, dateFormat, true);
        return fileDate2.isValid() && fileDate2.isBetween(fromMoment, toMoment, "day", "[]");
      }
      return false;
    }
    const basename = (_a = normalizedFilePath.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/i, "");
    if (!basename) {
      return false;
    }
    const fileDate = (0, import_obsidian6.moment)(basename, dateFormat, true);
    return fileDate.isValid() && fileDate.isBetween(fromMoment, toMoment, "day", "[]");
  });
}
async function writeJournalToFile(filePath, content, adapter, replaceExisting = false) {
  try {
    const folder = getParentDirectory(filePath);
    if (folder) {
      await ensureDirectoryExists(folder, adapter);
    }
    const fileExists = await adapter.exists(filePath);
    if (fileExists && !replaceExisting) {
      const newFilePath = await generateIncrementedFilePath(filePath, adapter);
      await adapter.write(newFilePath, content);
    } else {
      await adapter.write(filePath, content);
    }
  } catch (error) {
    console.error(`Error writing to journal file ${filePath}:`, error);
    throw new Error(`Failed to write to journal file: ${error instanceof Error ? error.message : String(error)}`);
  }
}
async function generateIncrementedFilePath(originalPath, adapter) {
  const lastDotIndex = originalPath.lastIndexOf(".");
  const basePath = lastDotIndex !== -1 ? originalPath.substring(0, lastDotIndex) : originalPath;
  const extension = lastDotIndex !== -1 ? originalPath.substring(lastDotIndex) : "";
  let counter = 1;
  let newPath = `${basePath}_${counter}${extension}`;
  while (await adapter.exists(newPath)) {
    counter++;
    newPath = `${basePath}_${counter}${extension}`;
  }
  return newPath;
}

// src/handlers/import-handler.ts
var import_obsidian7 = __toModule(require("obsidian"));
function validateImportSettings(settings) {
  if (!settings.dailyNotesFolder || !settings.hledgerFolder) {
    return "Please set both daily notes and Hledger folders in settings";
  }
  return null;
}
function groupTransactionsByDate(transactions, fromDate, toDate, hledgerDateFormat) {
  var _a;
  const transactionsByDate = new Map();
  const fromMoment = (0, import_obsidian7.moment)(fromDate, hledgerDateFormat);
  const toMoment = (0, import_obsidian7.moment)(toDate, hledgerDateFormat);
  for (const transaction of transactions) {
    const date = extractTransactionDate(transaction, hledgerDateFormat);
    if (!date)
      continue;
    const momentDate = (0, import_obsidian7.moment)(date, hledgerDateFormat);
    if (momentDate.isBetween(fromMoment, toMoment, "day", "[]")) {
      if (!transactionsByDate.has(date)) {
        transactionsByDate.set(date, []);
      }
      (_a = transactionsByDate.get(date)) == null ? void 0 : _a.push(transaction);
    }
  }
  return transactionsByDate;
}
function removeTransactionDates(transactions, hledgerDateFormat) {
  const dateRemovalRegex = createDateRemovalRegex(hledgerDateFormat);
  return transactions.map((transaction) => {
    const lines = transaction.split("\n");
    return lines.map((line, index) => {
      if (index === 0) {
        const processedLine = line.replace(dateRemovalRegex, "").trim();
        return processedLine || null;
      } else {
        return line.trim();
      }
    }).filter((line) => line !== null).join("\n");
  });
}
function processTransactions(transactions, includeDateInTransactions, hledgerDateFormat) {
  let processedTransactions = transactions;
  if (!includeDateInTransactions) {
    processedTransactions = removeTransactionDates(transactions, hledgerDateFormat);
  }
  return processedTransactions.filter((t) => t.trim()).join("\n\n") + "\n";
}
async function getTargetNotePath(date, hledgerDateFormat, dailyNotesDateFormat, dailyNotesFolder, adapter) {
  const momentDate = (0, import_obsidian7.moment)(date, hledgerDateFormat);
  let targetPath;
  if (dailyNotesDateFormat.includes("/")) {
    const [folderFormat, fileFormat] = dailyNotesDateFormat.split("/");
    const subFolder = momentDate.format(folderFormat);
    const fileName = momentDate.format(fileFormat) + ".md";
    const targetFolder = `${dailyNotesFolder}/${subFolder}`;
    await ensureDirectoryExists(targetFolder, adapter);
    targetPath = `${targetFolder}/${fileName}`;
  } else {
    const fileName = momentDate.format(dailyNotesDateFormat) + ".md";
    targetPath = `${dailyNotesFolder}/${fileName}`;
  }
  return targetPath;
}
async function writeTransactionsToNote(targetPath, transactionsContent, transactionHeader, adapter) {
  const fileExists = await adapter.exists(targetPath);
  let finalContent;
  if (fileExists) {
    const existingContent = await adapter.read(targetPath);
    const hledgerRegex = /```hledger\n([\s\S]*?)```/;
    if (existingContent.match(hledgerRegex)) {
      finalContent = existingContent.replace(hledgerRegex, `\`\`\`hledger
${transactionsContent}\`\`\``);
    } else {
      finalContent = existingContent.trimEnd() + `

${transactionHeader}

\`\`\`hledger
${transactionsContent}\`\`\``;
    }
  } else {
    finalContent = `${transactionHeader}

\`\`\`hledger
${transactionsContent}\`\`\``;
  }
  await adapter.write(targetPath, finalContent);
}
async function processTransactionsToDailyNotes(transactionsByDate, settings, adapter) {
  for (const [date, dateTransactions] of transactionsByDate) {
    const targetPath = await getTargetNotePath(date, settings.hledgerDateFormat, settings.dailyNotesDateFormat, settings.dailyNotesFolder, adapter);
    const processedTransactions = processTransactions(dateTransactions, settings.includeDateInTransactions, settings.hledgerDateFormat);
    await writeTransactionsToNote(targetPath, processedTransactions, settings.transactionHeader, adapter);
  }
}
function formatHledgerTransaction(dateObj, description, entries, settings, formatConfig, formatLineFn) {
  let content = "";
  if (settings.includeDateInTransactions) {
    content += dateObj.format(settings.hledgerDateFormat) + (description ? " " + description : "") + "\n";
  } else if (description) {
    content += description + "\n";
  }
  const padding = settings.includeDateInTransactions ? "    " : "";
  const isExchange = entries.length === 2 && entries[0].currency !== entries[1].currency && entries[0].amount !== 0 && entries[1].amount !== 0;
  if (isExchange) {
    content += padding + formatLineFn(entries[0].account, entries[0].amount, entries[0].currency, formatConfig) + "\n";
    content += padding + formatLineFn(entries[1].account, entries[0].amount > 0 && entries[1].amount > 0 ? -entries[1].amount : entries[1].amount, entries[1].currency, formatConfig, Math.abs(entries[0].amount), entries[0].currency) + "\n";
  } else {
    entries.forEach((entry) => {
      content += padding + formatLineFn(entry.account, entry.amount, entry.currency, formatConfig) + "\n";
    });
  }
  return content.trimEnd();
}

// src/main.ts
var HledgerPlugin = class extends import_obsidian8.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("dollar-sign", "Add hledger entry", () => {
      new HledgerEntryModal(this.app, this.settings, this.handleEntry.bind(this)).open();
    });
    this.addSettingTab(new HledgerSettingTab(this.app, this));
    this.addCommand({
      id: "add-hledger-entry",
      name: "Add hledger entry",
      callback: () => {
        new HledgerEntryModal(this.app, this.settings, this.handleEntry.bind(this)).open();
      }
    });
    this.addCommand({
      id: "export-hledger-journal",
      name: "Export transactions from daily notes to journal file",
      callback: () => {
        new HledgerExportModal(this.app, this.settings, this.handleExport.bind(this)).open();
      }
    });
    this.addCommand({
      id: "import-daily-transactions",
      name: "Import transactions from journal file to daily notes",
      callback: () => {
        new HledgerImportModal(this.app, this.settings, this.handleImport.bind(this)).open();
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async handleEntry(date, description, entries) {
    if (!this.settings.dailyNotesFolder) {
      new import_obsidian8.Notice("Please set a daily notes folder in settings");
      return;
    }
    const formatConfig = {
      numberFormat: this.settings.amountFormat,
      currencySpacing: this.settings.currencySpacing,
      currencyPlacement: this.settings.currencyPlacement,
      lineLength: this.settings.transactionLineLength
    };
    const dateObj = (0, import_obsidian8.moment)(date);
    const { targetFolder, targetPath } = calculateDailyNotePathInfo(dateObj, this.settings.dailyNotesFolder, this.settings.dailyNotesDateFormat);
    try {
      await ensureDirectoryExists(targetFolder, this.app.vault.adapter);
      const formattedTransaction = formatHledgerTransaction(dateObj, description, entries, {
        includeDateInTransactions: this.settings.includeDateInTransactions,
        hledgerDateFormat: this.settings.hledgerDateFormat
      }, formatConfig, formatLine);
      let content = formattedTransaction + "\n";
      await updateOrCreateDailyNoteHledgerSection(targetPath, content, this.settings.transactionHeader, this.app.vault.adapter);
      new import_obsidian8.Notice("hledger entry saved successfully");
    } catch (error) {
      console.error("Error saving hledger entry:", error);
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian8.Notice(`Error saving hledger entry: ${message}`);
    }
  }
  async handleExport(fromDate, toDate, fileName, replaceExisting) {
    const validationError = validateExportSettings(this.settings);
    if (validationError) {
      new import_obsidian8.Notice(validationError);
      return;
    }
    const adapter = this.app.vault.adapter;
    const dailyNotesFormat = this.settings.dailyNotesDateFormat;
    const hledgerFormat = this.settings.hledgerDateFormat;
    try {
      const allFiles = await getAllFilesInFolder(this.settings.dailyNotesFolder, adapter);
      const filteredFiles = filterFilesByDateRange(allFiles, fromDate, toDate, dailyNotesFormat);
      if (filteredFiles.length === 0) {
        new import_obsidian8.Notice("No daily notes found in the specified date range.");
        return;
      }
      const processedBlocks = await processHledgerFiles(filteredFiles, adapter, dailyNotesFormat, hledgerFormat);
      if (processedBlocks.length === 0) {
        new import_obsidian8.Notice("No hledger content found in the daily notes within the date range.");
        return;
      }
      const journalContent = processedBlocks.join("\n\n") + "\n";
      const exportFilePath = normalizePath(`${this.settings.hledgerFolder}/${fileName}`);
      await writeJournalToFile(exportFilePath, journalContent, adapter, replaceExisting);
      new import_obsidian8.Notice(`Journal exported successfully to ${exportFilePath}`);
    } catch (error) {
      console.error("Error during export:", error);
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian8.Notice(`Error exporting journal: ${message}`);
    }
  }
  async handleImport(fromDate, toDate, journalFile) {
    const validationError = validateImportSettings(this.settings);
    if (validationError) {
      new import_obsidian8.Notice(validationError);
      return;
    }
    const journalFilePath = normalizePath(`${this.settings.hledgerFolder}/${journalFile}`);
    const adapter = this.app.vault.adapter;
    new import_obsidian8.Notice(`Starting hledger journal import from ${journalFilePath}...`);
    if (!await adapter.exists(journalFilePath)) {
      new import_obsidian8.Notice(`Journal file not found at ${journalFilePath}`);
      return;
    }
    try {
      const journalContent = await adapter.read(journalFilePath);
      const transactions = parseJournalTransactions(journalContent, this.settings.hledgerDateFormat);
      const dateRangeTransactions = groupTransactionsByDate(transactions, fromDate, toDate, this.settings.hledgerDateFormat);
      await processTransactionsToDailyNotes(dateRangeTransactions, this.settings, adapter);
      new import_obsidian8.Notice("Daily transactions imported successfully");
    } catch (error) {
      console.error("Error importing daily transactions:", error);
      new import_obsidian8.Notice("Error importing daily transactions: " + error.message);
    }
  }
};

/* nosourcemap */